title: '@AWWWRY - My life. My work. And everything in between.'
logo:  # you can add own logo.
description: American-Indonesian father, fiancé, product designer and front-end engineer from Los Angeles, California.
keywords: Ary Mega, American-Indonesian, Balinese, Product Designer, UX Designer, Front-End Engineer, Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://awwwry.com" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: '@AWWWRY'
  image: '/assets/img/ary-mega.jpg'
  job: Just your typical Balinese web developer and designer who listens to country music in a Ford F-150.
  bio: American-Indonesian father, fiancé, product designer and front-end engineer from Los Angeles, California.
  email: arymega@gmail.com


# Contact links
contact:
  - name: GitHub
    link: https://github.com/awwwry
  - name: Instagram
    link: https://instagram.com/awwwry
  - name: LinkedIn
    link: https://linkedin.com/in/awwwry
  - name: Reddit
    link: https://reddit.com/u/awwwry
  - name: Twitter
    link: https://twitter.com/awwwry


# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-64088985-1 # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
