basic_settings:
  site_title: "@AWWWRY"
  favicon_image: /images/favicon.png

header_settings:
  logo_image:
  logo_width:

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Store'
      url: 'https://teespring.com/stores/awwwry'

footer_settings:
  logo_image: 
  logo_width: 100
  tagline: "<a href='https://www.google.com/search?sxsrf=ALeKk00IwGUmQE9Y-hJSstVeLIrysRnptg%3A1583135503972&source=hp&ei=D7tcXv-NOdb3-gSCz4CIBA&q=awwwry&oq=awwwry&gs_l=psy-ab.3..35i39l2j0i10l8.406.1256..1343...1.0..0.159.467.4j1......0....1..gws-wiz.......0i131j0.P6nl9yRwUrA&ved=0ahUKEwi_0d-qp_vnAhXWu54KHYInAEEQ4dUDCAc&uact=5' target='_blank'>Find me online.</a>"

hero_settings:
  background_image: /images/backgrounds/background-hero.svg

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: ''
  form_action: 'https://formspree.io/xjvrjkqd'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Holler'

social_settings:
  facebook_url: ''
  twitter_url: 'https://www.twitter.com/awwwry'
  instagram_url: 'https://www.instagram.com/awwwry'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://www.github.com/awwwry'
  reddit_url: 'https://www.reddit.com'
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: 'https://open.spotify.com/user/awwwry'
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/awwwry'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f8f8f8'
  text_dark_color: '#0D0D0D'
  text_medium_color: '#888888'
  text_light_color: '#D9D9D9'
  accent_color: '#F2CE1B'
  border_color: '#F2F2F2'
  error_color: '#F26241'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Rubik:wght@400;700&display=swap" rel="stylesheet">'
  title_font: '"Rubik", sans-serif'
  body_font: '"Rubik", sans-serif'
  regular_weight: 500
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 700
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 1.2
    line_height_small: 1.2
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 1.6
    line_height_small: 1.6
  h4:
    size: 32
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 45
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 700
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 1.6
    line_height_small: 1.6
  p:
    size: 20
    size_small: 16
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 1.6
  p_small:
    size: 16
    size_small: 14
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 30
    large_size: 38
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 700
    letter_spacing: 0.8

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""